export type PaymentMethodType = 'account' | 'credit_card';

export type TransactionType = 'expense' | 'income';

export interface FamilyMember {
  id: string;
  name: string;
  avatar: string;
  role: 'admin' | 'member';
  color: string;
}

export interface BankAccount {
  id: string;
  name: string;
  type: 'checking' | 'savings' | 'investment';
  balance: number;
  bankName: string;
  color: string;
}

export interface CreditCard {
  id: string;
  name: string;
  bankName: string;
  lastFourDigits: string;
  totalLimit: number;
  closingDay: number; // 1 to 31
  dueDay: number; // 1 to 31
  color: string; // Tailwind color class or hex
  brand: 'visa' | 'mastercard' | 'elo' | 'amex';
}

export interface Category {
  id: string;
  name: string;
  icon: string; // Lucide icon name string
  color: string;
  type: 'expense' | 'income' | 'both';
  budgetLimit?: number; // Monthly budget limit in BRL
}

export interface Transaction {
  id: string;
  description: string;
  amount: number;
  type: TransactionType;
  date: string; // YYYY-MM-DD
  categoryId: string;
  memberId: string;
  paymentMethod: PaymentMethodType;
  bankAccountId?: string; // If paymentMethod === 'account'
  creditCardId?: string;  // If paymentMethod === 'credit_card'
  
  // Installment fields
  installmentCurrent?: number; // e.g. 1
  installmentTotal?: number;   // e.g. 10
  parentTransactionId?: string; // Links installments together
  
  // Invoice target date
  invoiceMonthYear?: string; // "YYYY-MM" target invoice for credit purchases
  
  notes?: string;
  tags?: string[];
  isFixed?: boolean; // Recurrent expense/income
  isTransfer?: boolean; // True for the two legs generated by an account-to-account transfer
}

export interface Invoice {
  cardId: string;
  monthYear: string; // "YYYY-MM" (e.g. "2026-08")
  closingDate: string; // YYYY-MM-DD
  dueDate: string;     // YYYY-MM-DD
  status: 'open' | 'closed' | 'paid';
  totalAmount: number;
  paidAmount?: number;
  paidAt?: string;
  paidFromAccountId?: string;
}

export interface BudgetGoal {
  id: string;
  title: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string;
  category?: string;
}
